### ISSUE TITLE
Add add_* methods for further tag types

### ISSUE THREAD

**Issue by conqp** [skubalj/build_html#11]
I currently have this code in a project of mine:

```rust
use build_html::HtmlContainer;
use serde::Deserialize;

#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
pub struct Quote {
    elements: Vec<String>,
    author: String,
}

impl Quote {
    pub fn add_to(&self, parent: &mut impl HtmlContainer) {
        for element in &self.elements {
            parent.add_raw(format!("<blockquote>{element}</blockquote>"));
        }

        parent.add_raw(format!("<cite>-- {}</cite>", self.author));
    }
}
```
It would be nice, if one could do something like:
```rust
use build_html::HtmlContainer;
use serde::Deserialize;

#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
pub struct Quote {
    elements: Vec<String>,
    author: String,
}

impl Quote {
    pub fn add_to(&self, parent: &mut impl HtmlContainer) {
        for element in &self.elements {
            parent.add_blockquote(element);
        }

        parent.add_cite(format!("-- {}", self.author));
    }
}
```
I'd be happy to draft a PR if you'd be interested.

**Comment by skubalj** [comment]
Thanks for opening an issue! I'm sorry about the delay in getting to this -- I've been busy lately. I'm quite interested in bringing these additions into the library! It shouldn't be too difficult to add first class support for these tags.

I am curious, however, about what the design should look like. Based on the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote) for `<blockquote>`, it looks like putting a number of tags inside a block quote element is a "normal" thing to do. In that case, it might fit better as a variety of `ContainerType` so you can use the `HtmlContainer` methods to add content to it:
```rust
parent.add_container(
    Container::new(ContainerType::Blockquote)
        .with_html(element)
);
```

I'm not entirely sure what a `<cite>` tag should be either. From the examples I've seen, the "usual" use case for citations is to simply add text, so it would be a good candidate to add to the `HtmlContainer` interface. However, I'd rather not expose it to all implementors of `HtmlContainer` if the primary use is only for `<blockquote>` and `<q>` tags. In that case, I'd rather break these quotation tags out into a separate type with contextually appropriate children that can be inserted (similar to how tables are done).

What are your thoughts? How do you see these tags getting used in the wild?

**Comment by conqp** [comment]
Good questions. I have not frequently seen those tags out in the wild.
I will have a look over the upcoming weekend and report back with my findings.
Of course, if we implement this, it should be done the right way.

**Comment by skubalj** [comment]
I think the tags we were discussing here should be exposed via `HtmlElement` in v2.5.0. I'm closing this as done.
