### ISSUE TITLE
Add support for `<hr>` and `<br>`

### ISSUE THREAD

**Issue by 766F6964** [skubalj/build_html#13]
**Summary:**

Some really common tags present in many websites are the `<br>` and `<hr>`.
Currently, it seems the only way to add them is by using the `add_raw` or `with_raw` fn:
```rust
.with_raw("<hr>")
.add_raw("<br>")
```
I feel they should be provided by default by this library, given how common they are.
Something like `.with_hr()` or `.with_br()`, perhaps?

**Comment by skubalj** [comment]
This should be easily doable. I'll see about adding these at some point in the near future.
