### ISSUE TITLE
Add table footer methods

### ISSUE THREAD

**Issue by nricciardi** [skubalj/build_html#16]
Table does not have _footer methods_ such as `add_tfoot_attributes`, `add_footer_row` or `add_custom_footer_row`.

**Comment by nricciardi** [comment]
I created a pull request where I added those methods.
Thanks

**Comment by skubalj** [comment]
Thanks so much for opening up a PR! It looks like we have a couple failing tests, which I will address. I've merged your PR into a staging branch while I work on that, and I'll update this ticket when I've merged to main.

Regarding getting this published to crates.io: I've needed to update some documentation and get a new version out for a while now. I will make a point to put some time into this over the next week.

**Comment by skubalj** [comment]
Just a heads-up: this is merged to main. I have made a change so that the footer only appears when it has children or attributes set. That way, existing users who update to the next version will not see changes in their output.

**Comment by nricciardi** [comment]
Oh sorry. Honestly I did not think about it. Next time I'm going to watch code more in depth.

 I was happy to contribute to this project, even because I'm using it in my other project (pure Rust Markdown compiler) and I need the table footer.

I await the new version with interest. Thank you.
