### ISSUE TITLE
Attributes on table row and header

### ISSUE THREAD

**Issue by xorapps** [skubalj/build_html#6]
Add the ability to add attribute like classes, styles and id on <tr> and <td> 
like

```html
<table>
<tr style="padding: 10px">
<td class="foo" id="bar">
</td>
</tr>
```

**Comment by skubalj** [comment]
This is now implemented on `main`. Fair warning: I might end up refining this API slightly before releasing `v2.3.0`, but I believe that this is the path that I want to take for this:

```rust
let table = Table::new()
    .with_custom_body_row(
        TableRow::new()
            .with_attributes([("class", "long-row")])
            .with_cell(TableCell::default().with_raw("col1"))
            .with_cell(TableCell::default().with_raw("col2"))
            .with_cell(
                TableCell::default()
                    .with_attributes([("id", "third")])
                    .with_raw("col3")
            ),
    )
    .to_html_string();

assert_eq!(
    table,
    concat!(
        r#"<table><thead></thead><tbody><tr class="long-row">"#,
        r#"<td>col1</td><td>col2</td><td id="third">col3</td>"#,
        "</tr></tbody></table>",
    ),
);
```

Exposing table rows and cells as structs and using the `HtmlContainer` trait for `TableCell` makes the interface similar to the rest of the library (and makes the interface for nesting HTML inside tables nicer). Unfortunately, it's a lot more verbose than the `Table::from` implementation, but that's a tradeoff for having more granular control over the output. Overall, tables were never that well developed, so thanks for the impetus to improve them!
